### ISSUE TITLE
Dependency path not present unter arch

### ISSUE THREAD

**Issue by madonius** [fxkr/share-via-ssh#10]
There seems to be a gap in the documentation
> It only depends on Python 3, and optionally, the qrcode library.

This seems to not be true, at least on my system. Archlinux up-to-date on the 2017-03-07.
``` python
Traceback (most recent call last):
  File "./share-via-ssh", line 7, in <module>
    import path
ModuleNotFoundError: No module named 'path'
```

_Python Version_: 3.6.0

**Comment by fxkr** [comment]
My bad -- I confused https://pypi.python.org/pypi/path.py with https://docs.python.org/3/library/pathlib.html

Sometimes, flat is *not* better than nested, especially without a clear naming policy *sigh*. Say about Go's package referencing system what you want, but it gets *that* (mostly) right. Unlike Python.
